#!/bin/bash
#
# The script deletes current directory and launchers
# base version 01.12.2020 by Хрюнделёк
# version 02.02.2025 by Glenn Chugg
# https://www.lastos.org

# Initial set
dir="$(dirname "$(readlink -f "$0")")"
app="$(basename "$dir")"

#Remove LLStore folder name Suffix etc
app=$(echo "$app" | sed 's,\., ,g')
app=$(echo "$app" | sed 's,\_, ,g')
app=$(echo "$app" | sed 's,\LLGame, ,g')
app=$(echo "$app" | sed 's,\LLApp, ,g')
app=$(echo "$app" | xargs ) #Trim

#Make appdesktop the name of the file (Spaces converted back to .)
appdesktop=$(echo "$app" | sed 's,\ ,.,g')

# User environment launchers
if [ -z "$XDG_CONFIG_HOME" ]; then
	XDG_CONFIG_HOME=$HOME/.config
fi
# shellcheck source=/dev/null
. "$XDG_CONFIG_HOME"/user-dirs.dirs 2>/dev/null

if [ -z "$XDG_DATA_HOME" ]; then
	XDG_DATA_HOME=$HOME/.local/share
fi

if [ -z "$XDG_DESKTOP_DIR" ]; then
	XDG_DESKTOP_DIR=$HOME/Desktop
fi

#Check it's not a major directory (don't want to accidently run this script from the wrong path

echo "Testing removal of: $dir"

# ---- Safety: refuse to remove well-known protected locations ----
# The app name "Tools" is also blocked (common dev working directory).
if [ "$app" = "Tools" ]; then
    echo "Protected Folder"
    exit 1
fi

PROTECTED_DIRS=(
    "$HOME"
    "$XDG_DESKTOP_DIR"
    "$XDG_DATA_HOME"
    "$XDG_CONFIG_HOME"
    "/"
    "/etc"
    "/home"
    "/LastOS"
    "/opt/LastOS"
    "/opt"
    "/proc"
    "/srv"
    "/sys"
    "/tmp"
    "/usr"
    "/var"
    "/bin"
    "/sbin"
)
for _pd in "${PROTECTED_DIRS[@]}"; do
    [ -n "$_pd" ] || continue
    if [ "$dir" = "$_pd" ]; then
        echo "Protected Folder: $dir"
        exit 1
    fi
done
unset _pd

#If any above are true then it quits, Otherwise it will ask below to remove folder and links
#echo $appdesktop
#exit 1

desklauncher=$XDG_DESKTOP_DIR/$appdesktop.desktop
menudir=$XDG_DATA_HOME/applications
menulauncher=$menudir/$appdesktop.desktop
autostartlauncher=${XDG_CONFIG_HOME:-$HOME/.config}/autostart/$appdesktop.desktop

# Capture Path= from the main menu launcher before we delete it
main_path=""
if [ -f "$menulauncher" ]; then
	main_path=$(grep -m1 '^Path=' "$menulauncher" | cut -d= -f2- | tr -d '\r')
fi

# Returns 0 (true) only when $1 is a non-empty path that sits strictly inside
# one of the three allowed bases. Directory existence is NOT required — the
# Wine uninstaller may have already removed the folder before we run cleanup.
_is_allowed_path() {
	local p="$1"
	[ -z "$p" ] && return 1
	case "$p" in
		"$HOME/LLApps/"*|"$HOME/LLGames/"*|"$HOME/.wine/drive_c/"*)
			return 0 ;;
	esac
	return 1
}

# Scan $menudir recursively for any .desktop files whose Path= matches the
# one we just uninstalled and delete them (extra shortcuts for the same app).
# Handles Wine-generated files with Windows-style \r\n line endings.
_remove_extra_shortcuts() {
	local ref_path="$1"
	_is_allowed_path "$ref_path" || return
	local df p
	while IFS= read -r -d '' df; do
		# Strip trailing \r so Windows-style CRLF line endings don't break the compare
		p=$(grep -m1 '^Path=' "$df" | cut -d= -f2- | tr -d '\r')
		if [ "$p" = "$ref_path" ]; then
			rm -f "$df"
		fi
	done < <(find "$menudir" -name '*.desktop' -print0 2>/dev/null)
}

# Remove wine/Programs/<appname>/ .desktop files that were auto-generated by
# Wine's menu integration. These have no Path= line so they can't be matched
# by _remove_extra_shortcuts — instead we match by WINEPREFIX in their Exec=.
# ref_path must be a path under $HOME/.wine/drive_c/ for this to do anything.
_remove_wine_shortcuts() {
	local ref_path="$1"
	case "$ref_path" in
		"$HOME/.wine/drive_c/"*) ;;
		*) return ;;
	esac

	# Extract wine prefix:  /home/user/.wine/drive_c/foo/ -> /home/user/.wine
	local wineprefix="${ref_path%%/drive_c/*}"
	# Extract the app's directory name: /...Program Files/AIMP/ -> AIMP
	local app_folder
	app_folder=$(basename "${ref_path%/}")

	[ -z "$wineprefix" ] || [ -z "$app_folder" ] && return

	# Delete every .desktop in wine/Programs/<appname>/ that references this prefix
	local wine_prog_dir="$menudir/wine/Programs/$app_folder"
	[ -d "$wine_prog_dir" ] || return
	local df
	while IFS= read -r -d '' df; do
		if grep -q "WINEPREFIX=$wineprefix" "$df" 2>/dev/null; then
			rm -f "$df"
		fi
	done < <(find "$wine_prog_dir" -name '*.desktop' -print0 2>/dev/null)

	# Remove the now-empty Programs subfolder (and parent if empty too)
	rmdir "$wine_prog_dir"          2>/dev/null
}

# For ssApp installs the Windows uninstaller removes its own files but leaves
# behind LLStore metadata (ssApp.*, LLScript.sh, cover art etc.).
# Detect by checking for ssApp.* in $dir; remove known files, rmdir if empty.
# Falls back to rm -rf only for non-ssApp folders (ppApp/ppGame/LLGame etc.).
_remove_app_dir() {
	local d="$1"
	[ -d "$d" ] || return
	if ls "$d"/ssApp.* "$d"/LLScript.sh >/dev/null 2>&1; then
		rm -f "$d"/ssApp.cmd \
		      "$d"/ssApp.app \
		      "$d"/ssApp.ppg \
		      "$d"/ssApp.reg \
		      "$d"/ssApp.lla \
		      "$d"/ssApp.llg \
		      "$d"/ssApp.ico \
		      "$d"/ssApp.png \
		      "$d"/ssApp.jpg \
		      "$d"/ssApp.svg \
		      "$d"/ssApp.mp4 \
		      "$d"/LLScript.sh \
		      "$d"/uninstall.sh 2>/dev/null
		rmdir "$d" 2>/dev/null
	else
		rm -rf "$d"
	fi
}

# Localization
if (locale | grep -e 'ru_RU' >/dev/null); then
	title="Удаление"
	msg="Удалить"
	msg2="Удаляется"
	msg3="Готово."
	canc="Отмена."
else
	title="Uninstall"
	msg="Do you want to uninstall"
	msg2="Uninstalling"
	msg3="Done."
	canc="Canceled."
fi

# Prompt colors
red="\033[1;31m"
green="\033[1;32m"
reset="\033[0m"

# Check zenity & kdialog, otherwise run in the terminal
if command -v zenity >/dev/null; then
	if zenity --question --title="$title $app" --text="$msg $app?" \
--no-wrap >/dev/null 2>&1; then
		rm -f "$desklauncher" "$menulauncher" "$autostartlauncher"
		_remove_extra_shortcuts "$main_path"
		_remove_wine_shortcuts "$main_path"
		cd "$dir"/.. || exit
		_remove_app_dir "$dir" | zenity --progress --title="$title $app" \
--text="$msg2 $app..." --width=300 --pulsate --no-cancel --auto-close \
>/dev/null 2>&1
	else
		exit
	fi
	zenity --info --title="$title $app" --text="$msg3" --no-wrap \
>/dev/null 2>&1
	exit
elif command -v kdialog >/dev/null; then
	if kdialog --yesno "$msg $app?" --title="$title $app" >/dev/null \
2>&1; then
		rm -f "$desklauncher" "$menulauncher" "$autostartlauncher"
		_remove_extra_shortcuts "$main_path"
		_remove_wine_shortcuts "$main_path"
		cd "$dir"/.. || exit
		_remove_app_dir "$dir"
	else
		exit
	fi
	kdialog --msgbox "$msg3" --title="$title $app" >/dev/null 2>&1
	exit
else
	clear
	printf "\n%s  $msg $app? (y)es/(n)o:\n\n"
	read -r answer
	case "$answer" in
		[y])
			printf "\n%s$msg2 $app...\n"
			rm -f "$desklauncher" "$menulauncher" "$autostartlauncher"
			_remove_extra_shortcuts "$main_path"
			_remove_wine_shortcuts "$main_path"
			cd "$dir"/.. || exit
			_remove_app_dir "$dir"
			printf "\n%s${green}$msg3${reset}\n\n"
			;;
		*)
			printf "\n%s  ${red}$canc${reset}\n\n"
			exit
	esac
fi
exit 0
