#!/bin/bash

#Find the main Executable for your App and make sure the Parent folder name is clean and relevent.

CURRENT_PATH="$PWD"
CURRENT_EXEC="$@"
PARENT_FOLDER_NAME=$(basename "$CURRENT_PATH")

#gnome-terminal -- bash -c 'echo "Received variable: $1"; sleep 5' _ "$CURRENT_PATH"
#gnome-terminal -- bash -c 'echo "Received variable: $1"; sleep 5' _ "$CURRENT_EXEC"


cat >"$CURRENT_PATH/LLApp.lla" <<EOL
[LLFile]
Title=${PARENT_FOLDER_NAME}
Version=v1.0
Description=
URL=
Category=Other;
BuildType=LLApp
AppPath=%LLApps%/${PARENT_FOLDER_NAME}
Catalog=Other;
Priority=5
DECompatible=All-Linux
PMCompatible=All
ArchCompatible=x64
[Meta]
Releaser=LastOS
License=0
[${PARENT_FOLDER_NAME}.desktop]
Exec=%AppPath%/${CURRENT_EXEC}
Comment=
Icon=%LLApps%/${PARENT_FOLDER_NAME}/LLApp.png
Terminal=False
EOL

#Open in Editor
/LastOS/LLStore/llstore -e "$CURRENT_PATH/LLApp.lla"

#for f in "$@"
#do
#    /LastOS/LLStore/llstore -e $f
#done
